config/routes.rb
Rails.application.routes.draw do
  root "doctors#index"
  
  resources :doctors 
  resources :patients do
    resources :appointments, only: [:index, :new, :create, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient
end

app/models/doctor.rb
class Doctor < ApplicationRecord
    has_many :appointments, dependent: :destroy 
    has_many :patients, through: :appointments
end

app/models/patient.rb
class Patient < ApplicationRecord
has_many :appointments, dependent: :destroy 
has_many :doctors, through: :appointments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_patient
  def index
    @appointments = @patient.appointment.all
  end

  def new
    @appointment = @patient.appointment.new
    @doctors = Doctor.all
  end

  def create
    @appointment = @patient.appointments.new(appt_params)
    @doctors = Doctor.all
    if @appointment.save
      redirect_to patient_appts_path(@patient)
    else
      render :new 
    end
  end
  def destroy 
    @appointment = @patient.appointments.find(params[:id])
    @appointment.destroy 
    redirect_to patient_
  end 
  private
  def set_patient
    @patient = Patient.find(params[:patient_id])
  end
  def appt_params 
    params.requiere(:appointment).permit(:doctor_id)
  end 

end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :destroy, :create, :edit]

  def index
      @doctors = Doctor.all
      @patients =Patient.all
      @appointments =Appointment.all
  end

  def show
    @doctors = Doctor.all
  end

  def new
    @doctors = Doctor.new
  end
  def create 
    @doctor = Doctor.new(doctor_params)
    if @doctor.save 
      redirect_to @doctor 
    else 
      render :new
    end
  end

  def edit

  end
  def destroy 
    @doctor.destroy
    redirect_to doctors_path
  end

  private

  def set_doctor
    @doctor = Doctor.find(params[:id])
  end
  
  def doctor_params
    params.require(:doctor).permit(:name, :ocupation)
end
end

app/controllers/patient_controller.rb
class PatientController < ApplicationController
  before_action :set_patient, only: [:show, :destroy, :new]
  def index
    @patient = Patient.all
  end

  def show
  end

  def new
    @patient = Patient.new 
  end
  def create
    @patient = Patient(patient_param)
    if @petient.save
      redirect_to @patient
    else
      render :new
    end
    def destroy 
      @patient.destroy 
      redirect_to patients_path 
    end
  end
  private 
  def set_patient
    @patient = Patients.find(params[:id])
  end
  def patient_params
    params.requiere(:patient).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/patient_helper.rb
module PatientHelper
end

app/views/appointments/create.html.erb
<h1>Appointments#create</h1>
<p>Find me in app/views/appointments/create.html.erb</p>

app/views/appointments/index.html.erb
<h1>Appointments#index</h1>
<p>Find me in app/views/appointments/index.html.erb</p>

app/views/appointments/new.html.erb
<h1>Appointments#new</h1>
<p>Find me in app/views/appointments/new.html.erb</p>

app/views/doctors/edit.html.erb
<h1>Doctors#edit</h1>
<p>Find me in app/views/doctors/edit.html.erb</p>

app/views/doctors/index.html.erb
<h1>Home Admin</h1>
<div class="ui grid relaxed">
  <div style={width:600px}>
    <h1>Appointments</h1>
    <table class="ui celled table">
  <thead>
    <tr>
    <th>Doctor</th>
    <th>Patient</th>
    <th>Condition</th>
  </tr>
  </thead>
  <tbody>
  <%@appointments.each do |appt|%>
    <tr>
      <td data-label="Doctor"><%= appt.doctor.name%></td>
      <td data-label="Patient"><%=appt.patient.name%></td>
      <td data-label="Condition"><%=appt.patient.condition%></td>
    </tr>
    <%end%>
  </tbody>
</table>
  </div>
  <div class="two column row">
    <div class="column segment v-box">
      <h1>Doctors</h1>
       <div class="ui middle aligned animated list">
        <% @doctors.each do |doctor|%>
          <div class="item">
            <img class="ui avatar image" src="https://cdn1.iconfinder.com/data/icons/photography-2/512/YPS__human_avatar_portrait_photography_picture_photo-512.png">
            <div class="content">
              <div class="header"><%= doctor.name%></div>
              <%= doctor.ocupation%>
              <br/>
              <%= link_to "View", doctor_path(doctor) %>
              </div>
            </div>
            <%end%>
          </div>
        </div>
    <div class="column segment v-box">
      <h1>Patients</h1>
        <div class="ui middle aligned animated list">
          <% @patients.each do |patient|%>
            <div class="item">
            <img class="ui avatar image" src="https://cdn1.iconfinder.com/data/icons/photography-2/512/YPS__human_avatar_portrait_photography_picture_photo-512.png">
              <div class="content">
                <div class="header"><%= patient.name%></div>
                <%= patient.condition%>
                <br/>
                  <%= link_to "View", patient_path(patient)%>
              </div>
            </div>
            <%end%>
          </div>
        </div>
    </div>
   

app/views/doctors/new.html.erb
<%= form_for @doctors do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br />
  <%= f.label :ocupation %>
  <%= f.text_field :ocupation %><br />

  <%= f.submit %>
<% end %>

app/views/doctors/show.html.erb
<h1>Doctors#show</h1>
<p>Find me in app/views/doctors/show.html.erb</p>

app/views/layouts/_navbar.html.erb
<div class="ui three item menu">
  <%= link_to 'Home', doctors_path, class: "item"%>
  <%= link_to 'Add Doctor', new_doctor_path, class: "item"%>
  <%= link_to 'Add Patient', new_patient_path, class: "item"%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Appointments</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navbar' %>
  <div class='ui container'>

    <%= yield %>
  </body>
</html>

app/views/patient/index.html.erb
<h1>Patient#index</h1>
<p>Find me in app/views/patient/index.html.erb</p>

app/views/patient/new.html.erb
<h1>Patient#new</h1>

<%= form_for @patient do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br />

  <%= f.submit %>
<% end %>

app/views/patient/show.html.erb
<h1>Patient#show</h1>
<p>Find me in app/views/patient/show.html.erb</p>